kind: pipeline
name: default

steps:
- name: build
  image: node:10-alpine
  commands:
  - yarn install
  - yarn generate
- name: publish
  image: plugins/gh-pages
  settings:
    ssh_key:
      from_secret: GITHUB_SSH_KEY
    pages_directory: public/
